version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    depends_on:
      - redis
    environment:
      NODE_ENV: development # Or production
      REDIS_URL: redis://redis:6379
      # VAPID keys will be managed here or through a .env file loaded by docker-compose
      # VAPID_PUBLIC_KEY: "your_public_key_here" 
      # VAPID_PRIVATE_KEY: "your_private_key_here"
      # VAPID_SUBJECT: "mailto:your_email@example.com"
    volumes:
      - .:/app # Mount current directory to /app in container for development
      - /app/node_modules # Don't mount node_modules from host
      - /app/dist # Don't mount dist from host, use the one built in the container

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 