services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexbound-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
    env_file:
      - ./.env.prod
