services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexbound-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - postgres
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
    env_file:
      - ./.env.prod

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  redis_data:
  postgres_data:
