services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexbound-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.prod

  nginx:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt
